CREATE TABLE users (id uuid PRIMARY KEY, handle text NOT NULL UNIQUE, data jsonb NOT NULL);
CREATE TABLE user_sessions (token_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE studies (id uuid PRIMARY KEY, data jsonb NOT NULL);
CREATE TABLE study_members (study_id uuid NOT NULL REFERENCES studies(id),user_id uuid NOT NULL REFERENCES users(id),state text NOT NULL CHECK(state IN ('invited','joined')),inviter_user_id uuid NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(study_id,user_id));
CREATE TABLE experiences (id uuid PRIMARY KEY,owner_user_id uuid NOT NULL REFERENCES users(id),data jsonb NOT NULL);
CREATE TABLE experience_drafts (id uuid PRIMARY KEY,owner_user_id uuid NOT NULL REFERENCES users(id),data jsonb NOT NULL);
CREATE TABLE topics (id uuid PRIMARY KEY,study_id uuid NOT NULL REFERENCES studies(id),ordinal integer NOT NULL,data jsonb NOT NULL,generation_input jsonb,UNIQUE(study_id,ordinal));
CREATE TABLE transcript_segments (id uuid PRIMARY KEY,study_id uuid NOT NULL REFERENCES studies(id),topic_id uuid NOT NULL REFERENCES topics(id),speaker_user_id uuid NOT NULL REFERENCES users(id),start_order integer NOT NULL,data jsonb NOT NULL,UNIQUE(topic_id,start_order));
CREATE TABLE utterances (id uuid PRIMARY KEY,study_id uuid NOT NULL REFERENCES studies(id),topic_id uuid NOT NULL REFERENCES topics(id),speaker_user_id uuid NOT NULL REFERENCES users(id),data jsonb NOT NULL);
CREATE TABLE feedback (id uuid PRIMARY KEY REFERENCES utterances(id),data jsonb NOT NULL);
CREATE TABLE learning_items (id uuid PRIMARY KEY,owner_user_id uuid NOT NULL REFERENCES users(id),source_key text NOT NULL,data jsonb NOT NULL,UNIQUE(owner_user_id,source_key));
CREATE TABLE jobs (id uuid PRIMARY KEY,kind text NOT NULL,target_id uuid NOT NULL,status text NOT NULL,data jsonb NOT NULL,input jsonb);
CREATE UNIQUE INDEX jobs_active_generation ON jobs(target_id) WHERE kind='topic.generate' AND status='running';
CREATE TABLE chat_messages (id uuid PRIMARY KEY,owner_user_id uuid NOT NULL REFERENCES users(id),study_id uuid NOT NULL REFERENCES studies(id),client_message_id uuid,data jsonb NOT NULL,context jsonb,job_id uuid REFERENCES jobs(id),UNIQUE(owner_user_id,client_message_id));
CREATE TABLE share_proposals (id uuid PRIMARY KEY,owner_user_id uuid NOT NULL REFERENCES users(id),study_id uuid NOT NULL REFERENCES studies(id),learning_item_id uuid NOT NULL UNIQUE REFERENCES learning_items(id),data jsonb NOT NULL);
CREATE TABLE shared_expressions (id uuid PRIMARY KEY,study_id uuid NOT NULL REFERENCES studies(id),source_proposal_id uuid NOT NULL UNIQUE REFERENCES share_proposals(id),data jsonb NOT NULL);
CREATE TABLE command_receipts (actor_user_id uuid NOT NULL REFERENCES users(id),command_id uuid NOT NULL,route text NOT NULL,payload jsonb NOT NULL,result jsonb NOT NULL,PRIMARY KEY(actor_user_id,command_id));
CREATE TABLE media (id uuid PRIMARY KEY,study_id uuid NOT NULL REFERENCES studies(id),segment_id uuid REFERENCES transcript_segments(id),kind text NOT NULL CHECK(kind IN ('image','audio')),storage_key text NOT NULL,content_type text NOT NULL);
CREATE INDEX learning_items_owner ON learning_items(owner_user_id);
CREATE INDEX chat_messages_owner_study ON chat_messages(owner_user_id,study_id);
CREATE INDEX study_members_user ON study_members(user_id);
CREATE INDEX utterances_topic ON utterances(topic_id);
